import type { Source } from '../core/types.js';

/**
 * The source catalog.
 *
 * IMPORTANT - on `verified`:
 *
 * Every entry ships with `verified: false`. These URLs were written from
 * knowledge, not confirmed against the live hosts, because the environment this
 * was built in blocks all outbound HTTP. Feed URLs rot constantly - outlets
 * move to /rss, drop Atom, or put the feed behind Cloudflare.
 *
 * Run `all-int sources:check` on a machine with open network access. It
 * probes every entry, flips `verified` in the database for the ones that
 * answer, and prints the ones that do not so you can fix or drop them. Until
 * you do that, treat this list as a proposal rather than a working config.
 *
 * On selection: this leans hard toward primary records, because that is what
 * makes the connection engine work. A wire story saying a company won a
 * contract is useful; the award record with its obligation amount, agency, and
 * NAICS code is what a detector can actually join against a disclosed trade.
 */

type Draft = Omit<Source, 'verified' | 'enabled'> & { verified?: boolean; enabled?: boolean };

const def = (s: Draft): Source => ({ verified: false, enabled: true, ...s });

// ---------------------------------------------------------------------------
// Tier: primary - filings, registers, dockets, official releases
//
// This is the tier that makes the difference. Everything here is a record of
// something that happened, published by the body it happened to.
// ---------------------------------------------------------------------------

const PRIMARY: Source[] = [
  def({
    id: 'federal-register',
    name: 'Federal Register (rules, notices, presidential documents)',
    kind: 'federal-register',
    url: 'https://www.federalregister.gov/api/v1/documents.json',
    tier: 'primary',
    domains: ['politics', 'legal', 'business'],
    origin: 'US',
    lean: 'n/a',
    intervalMinutes: 180,
    notes: 'Free, no key. Every federal rule, proposed rule and notice. The spine of policy-then-beneficiary detection.',
  }),
  def({
    id: 'usaspending-awards',
    name: 'USASpending federal award announcements',
    kind: 'usaspending',
    url: 'https://api.usaspending.gov/api/v2/search/spending_by_award/',
    tier: 'primary',
    domains: ['defense', 'business', 'politics'],
    origin: 'US',
    lean: 'n/a',
    intervalMinutes: 360,
    notes: 'Free, no key, POST API. Contract and grant obligations with recipient, agency and amount.',
  }),
  def({
    id: 'dod-contracts',
    name: 'US Department of Defense daily contract announcements',
    kind: 'rss',
    url: 'https://www.defense.gov/DesktopModules/ArticleCS/RSS.ashx?ContentType=9&Site=945&max=40',
    tier: 'primary',
    domains: ['defense', 'business'],
    origin: 'US',
    lean: 'n/a',
    intervalMinutes: 360,
    notes: 'Every DoD award above the announcement threshold, published same day. Names contractor and value.',
  }),
  def({
    id: 'sec-edgar-form4',
    name: 'SEC EDGAR insider transactions (Form 4)',
    kind: 'sec-edgar',
    url: 'https://www.sec.gov/cgi-bin/browse-edgar?action=getcurrent&type=4&company=&dateb=&owner=include&count=100&output=atom',
    tier: 'primary',
    domains: ['markets', 'business'],
    origin: 'US',
    lean: 'n/a',
    intervalMinutes: 120,
    notes: 'Corporate insider buys and sells. Requires a descriptive User-Agent with contact email per SEC policy.',
  }),
  def({
    id: 'sec-edgar-8k',
    name: 'SEC EDGAR material events (8-K)',
    kind: 'sec-edgar',
    url: 'https://www.sec.gov/cgi-bin/browse-edgar?action=getcurrent&type=8-K&company=&dateb=&owner=include&count=100&output=atom',
    tier: 'primary',
    domains: ['business', 'markets'],
    origin: 'US',
    lean: 'n/a',
    intervalMinutes: 120,
    notes: 'Material corporate events, filed within four business days.',
  }),
  def({
    id: 'house-disclosures',
    name: 'US House financial disclosures (STOCK Act periodic transaction reports)',
    kind: 'stock-act',
    url: 'https://disclosures-clerk.house.gov/PublicDisclosure/FinancialDisclosure',
    tier: 'primary',
    domains: ['politics', 'markets'],
    origin: 'US',
    lean: 'n/a',
    intervalMinutes: 1440,
    notes: 'Annual ZIP of filing index plus per-filing PDFs. The congressional half of trade-then-award.',
  }),
  def({
    id: 'senate-disclosures',
    name: 'US Senate financial disclosures (STOCK Act periodic transaction reports)',
    kind: 'stock-act',
    url: 'https://efdsearch.senate.gov/search/',
    tier: 'primary',
    domains: ['politics', 'markets'],
    origin: 'US',
    lean: 'n/a',
    intervalMinutes: 1440,
    notes: 'Search form is session-cookie gated and requires accepting terms before querying.',
  }),
  def({
    id: 'congress-gov',
    name: 'Congress.gov legislation and votes',
    kind: 'json-api',
    url: 'https://api.congress.gov/v3/bill',
    tier: 'primary',
    domains: ['politics', 'legal'],
    origin: 'US',
    lean: 'n/a',
    intervalMinutes: 360,
    notes: 'Free API key from api.data.gov. Set CONGRESS_GOV_API_KEY.',
  }),
  def({
    id: 'whitehouse-actions',
    name: 'White House presidential actions',
    kind: 'rss',
    url: 'https://www.whitehouse.gov/presidential-actions/feed/',
    tier: 'primary',
    domains: ['politics', 'geopolitics'],
    origin: 'US',
    lean: 'state',
    intervalMinutes: 120,
    notes: 'Executive orders, proclamations, memoranda as issued.',
  }),
  def({
    id: 'treasury-ofac',
    name: 'US Treasury OFAC sanctions actions',
    kind: 'rss',
    url: 'https://ofac.treasury.gov/system/files/126/recent_actions.xml',
    tier: 'primary',
    domains: ['geopolitics', 'legal', 'intl-business'],
    origin: 'US',
    lean: 'n/a',
    intervalMinutes: 360,
    notes: 'Designations and delistings. High-signal for geopolitics-into-business links.',
  }),
  def({
    id: 'federal-reserve',
    name: 'Federal Reserve press releases',
    kind: 'rss',
    url: 'https://www.federalreserve.gov/feeds/press_all.xml',
    tier: 'primary',
    domains: ['macro', 'markets'],
    origin: 'US',
    lean: 'n/a',
    intervalMinutes: 180,
  }),
  def({
    id: 'ecb-press',
    name: 'European Central Bank press releases',
    kind: 'rss',
    url: 'https://www.ecb.europa.eu/rss/press.html',
    tier: 'primary',
    domains: ['macro', 'markets'],
    origin: 'EU',
    lean: 'n/a',
    intervalMinutes: 360,
  }),
  def({
    id: 'bls-releases',
    name: 'US Bureau of Labor Statistics releases',
    kind: 'rss',
    url: 'https://www.bls.gov/feed/bls_latest.rss',
    tier: 'primary',
    domains: ['macro'],
    origin: 'US',
    lean: 'n/a',
    intervalMinutes: 720,
  }),
  def({
    id: 'bea-releases',
    name: 'US Bureau of Economic Analysis releases',
    kind: 'rss',
    url: 'https://apps.bea.gov/rss/rss.xml',
    tier: 'primary',
    domains: ['macro'],
    origin: 'US',
    lean: 'n/a',
    intervalMinutes: 720,
  }),
  def({
    id: 'eia-today',
    name: 'US Energy Information Administration',
    kind: 'rss',
    url: 'https://www.eia.gov/rss/todayinenergy.xml',
    tier: 'primary',
    domains: ['energy', 'macro'],
    origin: 'US',
    lean: 'n/a',
    intervalMinutes: 720,
  }),
  def({
    id: 'ustr',
    name: 'US Trade Representative press',
    kind: 'rss',
    url: 'https://ustr.gov/rss.xml',
    tier: 'primary',
    domains: ['intl-business', 'geopolitics'],
    origin: 'US',
    lean: 'state',
    intervalMinutes: 360,
  }),
  def({
    id: 'state-dept',
    name: 'US State Department press releases',
    kind: 'rss',
    url: 'https://www.state.gov/rss-feed/press-releases/feed/',
    tier: 'primary',
    domains: ['geopolitics'],
    origin: 'US',
    lean: 'state',
    intervalMinutes: 240,
  }),
  def({
    id: 'doj-press',
    name: 'US Department of Justice press releases',
    kind: 'rss',
    url: 'https://www.justice.gov/news/rss',
    tier: 'primary',
    domains: ['legal', 'politics', 'business'],
    origin: 'US',
    lean: 'n/a',
    intervalMinutes: 240,
    notes: 'Indictments, antitrust actions, settlements.',
  }),
  def({
    id: 'ftc-press',
    name: 'US Federal Trade Commission press releases',
    kind: 'rss',
    url: 'https://www.ftc.gov/feeds/press-release.xml',
    tier: 'primary',
    domains: ['business', 'tech', 'legal'],
    origin: 'US',
    lean: 'n/a',
    intervalMinutes: 360,
  }),
  def({
    id: 'courtlistener-opinions',
    name: 'CourtListener federal opinions',
    kind: 'json-api',
    url: 'https://www.courtlistener.com/api/rest/v4/opinions/',
    tier: 'primary',
    domains: ['legal'],
    origin: 'US',
    lean: 'n/a',
    intervalMinutes: 720,
    notes: 'Free API token from courtlistener.com. Set COURTLISTENER_API_TOKEN.',
  }),
  def({
    id: 'gao-reports',
    name: 'US Government Accountability Office reports',
    kind: 'rss',
    url: 'https://www.gao.gov/rss/reports.xml',
    tier: 'primary',
    domains: ['politics', 'defense'],
    origin: 'US',
    lean: 'n/a',
    intervalMinutes: 1440,
    notes: 'Audits of exactly the procurement behaviour this tool is built to notice.',
  }),
  def({
    id: 'eu-official-journal',
    name: 'EUR-Lex Official Journal (L series)',
    kind: 'rss',
    url: 'https://eur-lex.europa.eu/EN/display-feed.rss?myRssId=oj-l',
    tier: 'primary',
    domains: ['legal', 'politics', 'intl-business'],
    origin: 'EU',
    lean: 'n/a',
    intervalMinutes: 720,
  }),
  def({
    id: 'ec-press',
    name: 'European Commission press corner',
    kind: 'rss',
    url: 'https://ec.europa.eu/commission/presscorner/api/rss?language=en',
    tier: 'primary',
    domains: ['politics', 'intl-business', 'tech'],
    origin: 'EU',
    lean: 'state',
    intervalMinutes: 360,
  }),
  def({
    id: 'uk-gov',
    name: 'UK Government announcements',
    kind: 'rss',
    url: 'https://www.gov.uk/search/news-and-communications.atom',
    tier: 'primary',
    domains: ['politics', 'geopolitics'],
    origin: 'UK',
    lean: 'state',
    intervalMinutes: 360,
  }),
  def({
    id: 'imf-news',
    name: 'IMF news and country reports',
    kind: 'rss',
    url: 'https://www.imf.org/en/News/RSS?language=eng',
    tier: 'primary',
    domains: ['macro', 'intl-business'],
    origin: 'INTL',
    lean: 'n/a',
    intervalMinutes: 720,
  }),
  def({
    id: 'worldbank-news',
    name: 'World Bank news',
    kind: 'rss',
    url: 'https://www.worldbank.org/en/news/all?format=rss',
    tier: 'primary',
    domains: ['macro', 'intl-business'],
    origin: 'INTL',
    lean: 'n/a',
    intervalMinutes: 1440,
  }),
  def({
    id: 'un-news',
    name: 'UN News global perspective',
    kind: 'rss',
    url: 'https://news.un.org/feed/subscribe/en/news/all/rss.xml',
    tier: 'primary',
    domains: ['geopolitics'],
    origin: 'INTL',
    lean: 'n/a',
    intervalMinutes: 360,
  }),
  def({
    id: 'nato-news',
    name: 'NATO news',
    kind: 'rss',
    url: 'https://www.nato.int/cps/en/natolive/news.rss',
    tier: 'primary',
    domains: ['defense', 'geopolitics'],
    origin: 'INTL',
    lean: 'state',
    intervalMinutes: 720,
  }),
  def({
    id: 'wto-news',
    name: 'World Trade Organization news',
    kind: 'rss',
    url: 'https://www.wto.org/library/rss/latest_news_e.xml',
    tier: 'primary',
    domains: ['intl-business', 'geopolitics'],
    origin: 'INTL',
    lean: 'n/a',
    intervalMinutes: 1440,
  }),
];

// ---------------------------------------------------------------------------
// Tier: wire
// ---------------------------------------------------------------------------

const WIRE: Source[] = [
  def({
    id: 'reuters-world',
    name: 'Reuters world news',
    kind: 'rss',
    url: 'https://www.reuters.com/arc/outboundfeeds/rss/category/world/?outputType=xml',
    tier: 'wire',
    domains: ['geopolitics', 'politics'],
    origin: 'UK',
    lean: 'center',
    intervalMinutes: 30,
    notes: 'Reuters has repeatedly changed its feed paths; expect to fix this URL.',
  }),
  def({
    id: 'reuters-business',
    name: 'Reuters business news',
    kind: 'rss',
    url: 'https://www.reuters.com/arc/outboundfeeds/rss/category/business/?outputType=xml',
    tier: 'wire',
    domains: ['business', 'intl-business', 'markets'],
    origin: 'UK',
    lean: 'center',
    intervalMinutes: 30,
  }),
  def({
    id: 'ap-topnews',
    name: 'Associated Press top news',
    kind: 'rss',
    url: 'https://feeds.apnews.com/rss/apf-topnews',
    tier: 'wire',
    domains: ['politics', 'geopolitics'],
    origin: 'US',
    lean: 'center',
    intervalMinutes: 30,
    notes: 'AP has withdrawn public RSS at times; verify before relying on it.',
  }),
  def({
    id: 'aljazeera-all',
    name: 'Al Jazeera English',
    kind: 'rss',
    url: 'https://www.aljazeera.com/xml/rss/all.xml',
    tier: 'wire',
    domains: ['geopolitics'],
    origin: 'QA',
    lean: 'center-left',
    intervalMinutes: 60,
    notes: 'Non-Western vantage on Middle East and Global South stories.',
  }),
  def({
    id: 'dw-top',
    name: 'Deutsche Welle top stories',
    kind: 'rss',
    url: 'https://rss.dw.com/rdf/rss-en-all',
    tier: 'wire',
    domains: ['geopolitics', 'politics'],
    origin: 'DE',
    lean: 'center',
    intervalMinutes: 60,
  }),
  def({
    id: 'france24',
    name: 'France 24 English',
    kind: 'rss',
    url: 'https://www.france24.com/en/rss',
    tier: 'wire',
    domains: ['geopolitics'],
    origin: 'FR',
    lean: 'center',
    intervalMinutes: 60,
  }),
  def({
    id: 'kyodo',
    name: 'Kyodo News English',
    kind: 'rss',
    url: 'https://english.kyodonews.net/rss/news',
    tier: 'wire',
    domains: ['geopolitics', 'intl-business'],
    origin: 'JP',
    lean: 'center',
    intervalMinutes: 120,
  }),
  def({
    id: 'tass-en',
    name: 'TASS English (Russian state)',
    kind: 'rss',
    url: 'https://tass.com/rss/v2.xml',
    tier: 'wire',
    domains: ['geopolitics'],
    origin: 'RU',
    lean: 'state',
    intervalMinutes: 180,
    notes: 'State outlet. Carried for what Moscow chooses to say, never as fact on its own.',
  }),
  def({
    id: 'xinhua-en',
    name: 'Xinhua English (Chinese state)',
    kind: 'rss',
    url: 'https://english.news.cn/rss/world.xml',
    tier: 'wire',
    domains: ['geopolitics', 'intl-business'],
    origin: 'CN',
    lean: 'state',
    intervalMinutes: 180,
    notes: 'State outlet. Same caveat as TASS.',
  }),
];

// ---------------------------------------------------------------------------
// Tier: outlet
// ---------------------------------------------------------------------------

const OUTLET: Source[] = [
  def({
    id: 'ft-world',
    name: 'Financial Times world',
    kind: 'rss',
    url: 'https://www.ft.com/world?format=rss',
    tier: 'outlet',
    domains: ['intl-business', 'geopolitics', 'markets'],
    origin: 'UK',
    lean: 'center',
    intervalMinutes: 60,
    notes: 'Headlines and standfirsts only without a subscription; body text is paywalled.',
  }),
  def({
    id: 'economist-intl',
    name: 'The Economist international',
    kind: 'rss',
    url: 'https://www.economist.com/international/rss.xml',
    tier: 'outlet',
    domains: ['geopolitics', 'intl-business'],
    origin: 'UK',
    lean: 'center',
    intervalMinutes: 360,
  }),
  def({
    id: 'guardian-world',
    name: 'The Guardian world',
    kind: 'rss',
    url: 'https://www.theguardian.com/world/rss',
    tier: 'outlet',
    domains: ['geopolitics', 'politics'],
    origin: 'UK',
    lean: 'center-left',
    intervalMinutes: 60,
    notes: 'Full text in feed, no paywall. One of the most complete free feeds available.',
  }),
  def({
    id: 'bbc-world',
    name: 'BBC News world',
    kind: 'rss',
    url: 'https://feeds.bbci.co.uk/news/world/rss.xml',
    tier: 'outlet',
    domains: ['geopolitics', 'politics'],
    origin: 'UK',
    lean: 'center',
    intervalMinutes: 45,
  }),
  def({
    id: 'nyt-world',
    name: 'New York Times world',
    kind: 'rss',
    url: 'https://rss.nytimes.com/services/xml/rss/nyt/World.xml',
    tier: 'outlet',
    domains: ['geopolitics', 'politics'],
    origin: 'US',
    lean: 'center-left',
    intervalMinutes: 60,
  }),
  def({
    id: 'nyt-business',
    name: 'New York Times business',
    kind: 'rss',
    url: 'https://rss.nytimes.com/services/xml/rss/nyt/Business.xml',
    tier: 'outlet',
    domains: ['business', 'markets'],
    origin: 'US',
    lean: 'center-left',
    intervalMinutes: 60,
  }),
  def({
    id: 'wapo-politics',
    name: 'Washington Post politics',
    kind: 'rss',
    url: 'https://feeds.washingtonpost.com/rss/politics',
    tier: 'outlet',
    domains: ['politics'],
    origin: 'US',
    lean: 'center-left',
    intervalMinutes: 60,
  }),
  def({
    id: 'politico',
    name: 'Politico',
    kind: 'rss',
    url: 'https://rss.politico.com/politics-news.xml',
    tier: 'outlet',
    domains: ['politics'],
    origin: 'US',
    lean: 'center',
    intervalMinutes: 60,
  }),
  def({
    id: 'axios',
    name: 'Axios',
    kind: 'rss',
    url: 'https://api.axios.com/feed/',
    tier: 'outlet',
    domains: ['politics', 'business', 'tech'],
    origin: 'US',
    lean: 'center',
    intervalMinutes: 60,
  }),
  def({
    id: 'semafor',
    name: 'Semafor',
    kind: 'rss',
    url: 'https://www.semafor.com/rss.xml',
    tier: 'outlet',
    domains: ['politics', 'intl-business', 'geopolitics'],
    origin: 'US',
    lean: 'center',
    intervalMinutes: 180,
  }),
  def({
    id: 'nikkei-asia',
    name: 'Nikkei Asia',
    kind: 'rss',
    url: 'https://asia.nikkei.com/rss/feed/nar',
    tier: 'outlet',
    domains: ['intl-business', 'geopolitics', 'tech'],
    origin: 'JP',
    lean: 'center',
    intervalMinutes: 180,
    notes: 'Best free-ish coverage of Asian supply chains and semiconductor politics.',
  }),
  def({
    id: 'scmp-news',
    name: 'South China Morning Post',
    kind: 'rss',
    url: 'https://www.scmp.com/rss/91/feed',
    tier: 'outlet',
    domains: ['geopolitics', 'intl-business'],
    origin: 'HK',
    lean: 'center',
    intervalMinutes: 180,
  }),
  def({
    id: 'lemonde-en',
    name: 'Le Monde English',
    kind: 'rss',
    url: 'https://www.lemonde.fr/en/rss/une.xml',
    tier: 'outlet',
    domains: ['geopolitics', 'politics'],
    origin: 'FR',
    lean: 'center-left',
    intervalMinutes: 180,
  }),
  def({
    id: 'spiegel-en',
    name: 'Der Spiegel International',
    kind: 'rss',
    url: 'https://www.spiegel.de/international/index.rss',
    tier: 'outlet',
    domains: ['geopolitics', 'politics'],
    origin: 'DE',
    lean: 'center-left',
    intervalMinutes: 360,
  }),
  def({
    id: 'haaretz-en',
    name: 'Haaretz English',
    kind: 'rss',
    url: 'https://www.haaretz.com/srv/htz---all-articles',
    tier: 'outlet',
    domains: ['geopolitics'],
    origin: 'IL',
    lean: 'center-left',
    intervalMinutes: 360,
  }),
  def({
    id: 'thehindu-intl',
    name: 'The Hindu international',
    kind: 'rss',
    url: 'https://www.thehindu.com/news/international/feeder/default.rss',
    tier: 'outlet',
    domains: ['geopolitics'],
    origin: 'IN',
    lean: 'center',
    intervalMinutes: 360,
  }),
  def({
    id: 'restofworld',
    name: 'Rest of World',
    kind: 'rss',
    url: 'https://restofworld.org/feed/latest/',
    tier: 'outlet',
    domains: ['tech', 'intl-business'],
    origin: 'US',
    lean: 'center',
    intervalMinutes: 720,
    notes: 'Technology outside the US and China. Fills a real gap.',
  }),
  def({
    id: 'arstechnica',
    name: 'Ars Technica',
    kind: 'rss',
    url: 'https://feeds.arstechnica.com/arstechnica/index',
    tier: 'outlet',
    domains: ['tech'],
    origin: 'US',
    lean: 'center',
    intervalMinutes: 180,
  }),
  def({
    id: 'theregister',
    name: 'The Register',
    kind: 'rss',
    url: 'https://www.theregister.com/headlines.atom',
    tier: 'outlet',
    domains: ['tech', 'business'],
    origin: 'UK',
    lean: 'center',
    intervalMinutes: 180,
  }),
];

// ---------------------------------------------------------------------------
// Tier: research - academic, institutional, investigative
// ---------------------------------------------------------------------------

const RESEARCH: Source[] = [
  def({
    id: 'lawfare',
    name: 'Lawfare',
    kind: 'rss',
    url: 'https://www.lawfaremedia.org/feeds/all',
    tier: 'research',
    domains: ['legal', 'defense', 'geopolitics'],
    origin: 'US',
    lean: 'center',
    intervalMinutes: 360,
    notes: 'National security law, written by practitioners. Explains legal mechanics other outlets skip.',
  }),
  def({
    id: 'warontherocks',
    name: 'War on the Rocks',
    kind: 'rss',
    url: 'https://warontherocks.com/feed/',
    tier: 'research',
    domains: ['defense', 'geopolitics'],
    origin: 'US',
    lean: 'center',
    intervalMinutes: 720,
  }),
  def({
    id: 'isw',
    name: 'Institute for the Study of War campaign assessments',
    kind: 'rss',
    url: 'https://www.understandingwar.org/feeds/all.xml',
    tier: 'research',
    domains: ['defense', 'geopolitics'],
    origin: 'US',
    lean: 'center-right',
    intervalMinutes: 720,
    notes: 'Daily geolocated assessments of active conflicts.',
  }),
  def({
    id: 'csis',
    name: 'Center for Strategic and International Studies',
    kind: 'rss',
    url: 'https://www.csis.org/analysis/feed',
    tier: 'research',
    domains: ['geopolitics', 'defense', 'intl-business'],
    origin: 'US',
    lean: 'center',
    intervalMinutes: 1440,
  }),
  def({
    id: 'carnegie',
    name: 'Carnegie Endowment for International Peace',
    kind: 'rss',
    url: 'https://carnegieendowment.org/rss/publications',
    tier: 'research',
    domains: ['geopolitics'],
    origin: 'US',
    lean: 'center',
    intervalMinutes: 1440,
  }),
  def({
    id: 'brookings',
    name: 'Brookings Institution research',
    kind: 'rss',
    url: 'https://www.brookings.edu/feed/',
    tier: 'research',
    domains: ['politics', 'macro', 'geopolitics'],
    origin: 'US',
    lean: 'center-left',
    intervalMinutes: 1440,
  }),
  def({
    id: 'chathamhouse',
    name: 'Chatham House',
    kind: 'rss',
    url: 'https://www.chathamhouse.org/rss/publications',
    tier: 'research',
    domains: ['geopolitics'],
    origin: 'UK',
    lean: 'center',
    intervalMinutes: 1440,
  }),
  def({
    id: 'piie',
    name: 'Peterson Institute for International Economics',
    kind: 'rss',
    url: 'https://www.piie.com/rss/research',
    tier: 'research',
    domains: ['macro', 'intl-business'],
    origin: 'US',
    lean: 'center',
    intervalMinutes: 1440,
    notes: 'The serious quantitative shop on tariffs and trade.',
  }),
  def({
    id: 'bruegel',
    name: 'Bruegel',
    kind: 'rss',
    url: 'https://www.bruegel.org/rss.xml',
    tier: 'research',
    domains: ['macro', 'intl-business'],
    origin: 'EU',
    lean: 'center',
    intervalMinutes: 1440,
  }),
  def({
    id: 'ecfr',
    name: 'European Council on Foreign Relations',
    kind: 'rss',
    url: 'https://ecfr.eu/feed/',
    tier: 'research',
    domains: ['geopolitics'],
    origin: 'EU',
    lean: 'center',
    intervalMinutes: 1440,
  }),
  def({
    id: 'rusi',
    name: 'Royal United Services Institute',
    kind: 'rss',
    url: 'https://rusi.org/rss/commentary',
    tier: 'research',
    domains: ['defense', 'geopolitics'],
    origin: 'UK',
    lean: 'center',
    intervalMinutes: 1440,
  }),
  def({
    id: 'nber',
    name: 'NBER new working papers',
    kind: 'rss',
    url: 'https://back.nber.org/rss/new.xml',
    tier: 'research',
    domains: ['macro', 'business'],
    origin: 'US',
    lean: 'n/a',
    intervalMinutes: 1440,
    notes: 'Where the economics that later becomes policy shows up first.',
  }),
  def({
    id: 'voxeu',
    name: 'CEPR VoxEU columns',
    kind: 'rss',
    url: 'https://cepr.org/rss/voxeu.xml',
    tier: 'research',
    domains: ['macro', 'intl-business'],
    origin: 'EU',
    lean: 'n/a',
    intervalMinutes: 1440,
  }),
  def({
    id: 'arxiv-econ-gn',
    name: 'arXiv general economics',
    kind: 'rss',
    url: 'https://rss.arxiv.org/rss/econ.GN',
    tier: 'research',
    domains: ['macro'],
    origin: 'INTL',
    lean: 'n/a',
    intervalMinutes: 1440,
  }),
  def({
    id: 'arxiv-cs-ai',
    name: 'arXiv artificial intelligence',
    kind: 'rss',
    url: 'https://rss.arxiv.org/rss/cs.AI',
    tier: 'research',
    domains: ['tech'],
    origin: 'INTL',
    lean: 'n/a',
    intervalMinutes: 1440,
    notes: 'High volume. Consider filtering before extraction or it will dominate the corpus.',
  }),
  // ---------------------------------------------------------------------------
  // Civil society and specialist monitors.
  //
  // These publish the material professional analysis runs on - lobbying
  // registrations, beneficial ownership, profit shifting, revolving-door
  // tracking. A corpus of governments and newspapers reports decisions; these
  // bodies report the money and the ownership behind them, which is where a
  // non-obvious read usually comes from. Slow-moving by design, so daily polls.
  //
  // NOT HERE, AND THEY SHOULD BE. SIPRI (arms transfers), Transparency
  // International (procurement, beneficial ownership), Global Witness
  // (extractives supply chains), IEA and IRENA (capacity and cost curves) and
  // IISS (order of battle) publish no discoverable RSS - their material lives
  // in databases and PDF yearbooks. Each needs its own adapter, the way
  // usaspending and stock-act have one. SIPRI is the highest value of them:
  // arms-transfer data is the counterparty side of every defence award this
  // corpus already ingests. Recorded here so the gap is a known absence rather
  // than an oversight.
  // ---------------------------------------------------------------------------
  def({
    id: 'opensecrets',
    name: 'OpenSecrets money in politics',
    kind: 'rss',
    url: 'https://www.opensecrets.org/news/feed',
    tier: 'research',
    domains: ['politics', 'business'],
    origin: 'US',
    lean: 'n/a',
    intervalMinutes: 1440,
    notes: 'Lobbying and campaign finance. Who paid to be in the room before a rule moved.',
  }),
  def({
    id: 'tax-justice',
    name: 'Tax Justice Network',
    kind: 'rss',
    url: 'https://taxjustice.net/feed/',
    tier: 'research',
    domains: ['intl-business', 'macro', 'legal'],
    origin: 'UK',
    lean: 'n/a',
    intervalMinutes: 1440,
    notes: 'Profit shifting and secrecy jurisdictions - the structures a filing does not show.',
  }),
  def({
    id: 'public-citizen',
    name: 'Public Citizen',
    kind: 'rss',
    url: 'https://www.citizen.org/feed/',
    tier: 'research',
    domains: ['politics', 'legal', 'business'],
    origin: 'US',
    lean: 'left',
    intervalMinutes: 1440,
    notes: 'Regulatory capture and revolving-door tracking, often ahead of the trade press.',
  }),
  def({
    id: 'hrw-news',
    name: 'Human Rights Watch',
    kind: 'rss',
    url: 'https://www.hrw.org/rss/news',
    tier: 'research',
    domains: ['geopolitics', 'legal', 'politics'],
    origin: 'US',
    lean: 'n/a',
    intervalMinutes: 1440,
    notes: 'Country-level reporting that often precedes sanctions and export-control moves.',
  }),
  def({
    id: 'amnesty-news',
    name: 'Amnesty International',
    kind: 'rss',
    url: 'https://www.amnesty.org/en/feed/',
    tier: 'research',
    domains: ['geopolitics', 'legal'],
    origin: 'UK',
    lean: 'n/a',
    intervalMinutes: 1440,
    notes: 'Same function as HRW; kept separately because they diverge on which states they press.',
  }),
  def({
    id: 'occrp',
    name: 'Organized Crime and Corruption Reporting Project',
    kind: 'rss',
    url: 'https://www.occrp.org/en/feed',
    tier: 'research',
    domains: ['legal', 'intl-business', 'politics'],
    origin: 'INTL',
    lean: 'n/a',
    intervalMinutes: 1440,
    notes: 'Cross-border investigative work on exactly the money flows this tool looks for.',
  }),
  def({
    id: 'icij',
    name: 'International Consortium of Investigative Journalists',
    kind: 'rss',
    url: 'https://www.icij.org/feed/',
    tier: 'research',
    domains: ['intl-business', 'legal', 'politics'],
    origin: 'INTL',
    lean: 'n/a',
    intervalMinutes: 1440,
  }),
  def({
    id: 'bellingcat',
    name: 'Bellingcat',
    kind: 'rss',
    url: 'https://www.bellingcat.com/feed/',
    tier: 'research',
    domains: ['geopolitics', 'defense'],
    origin: 'INTL',
    lean: 'n/a',
    intervalMinutes: 1440,
    notes: 'Open-source verification. Method is published alongside conclusions.',
  }),
  def({
    id: 'foreignaffairs',
    name: 'Foreign Affairs',
    kind: 'rss',
    url: 'https://www.foreignaffairs.com/rss.xml',
    tier: 'research',
    domains: ['geopolitics'],
    origin: 'US',
    lean: 'center',
    intervalMinutes: 1440,
  }),
];

// ---------------------------------------------------------------------------
// Prediction markets - the base-rate anchor for forecasting
// ---------------------------------------------------------------------------

const MARKETS: Source[] = [
  def({
    id: 'polymarket',
    name: 'Polymarket open markets',
    kind: 'prediction-market',
    url: 'https://gamma-api.polymarket.com/markets',
    tier: 'primary',
    domains: ['politics', 'geopolitics', 'markets'],
    origin: 'INTL',
    lean: 'n/a',
    intervalMinutes: 360,
    notes: 'Free, no key. Prices are the crowd base rate to check our own forecasts against.',
  }),
  def({
    id: 'kalshi',
    name: 'Kalshi markets',
    kind: 'prediction-market',
    url: 'https://api.elections.kalshi.com/trade-api/v2/markets',
    tier: 'primary',
    domains: ['politics', 'macro', 'markets'],
    origin: 'US',
    lean: 'n/a',
    intervalMinutes: 360,
    notes: 'CFTC-regulated. Public read endpoints do not need auth.',
  }),
  def({
    id: 'metaculus',
    name: 'Metaculus questions',
    kind: 'prediction-market',
    url: 'https://www.metaculus.com/api2/questions/',
    tier: 'research',
    domains: ['geopolitics', 'tech', 'macro'],
    origin: 'INTL',
    lean: 'n/a',
    intervalMinutes: 720,
    notes: 'Forecaster consensus rather than money. Better on long-horizon questions.',
  }),
];

export const REGISTRY: Source[] = [...PRIMARY, ...WIRE, ...OUTLET, ...RESEARCH, ...MARKETS];

export function registryById(id: string): Source | undefined {
  return REGISTRY.find((s) => s.id === id);
}

export function registryStats(): Record<string, number> {
  const byTier: Record<string, number> = {};
  for (const s of REGISTRY) byTier[s.tier] = (byTier[s.tier] ?? 0) + 1;
  return { total: REGISTRY.length, ...byTier };
}
